### ISSUE TITLE
Strange/hard-to-explain behavior with Matrix3 round-trips

### ISSUE THREAD

**Issue by focustense** [SteveTownsend/niflyswig#6]
There's a good chance I'm just using these APIs incorrectly or making some bad assumptions, as I have only an elementary understanding of 3D graphics and matrix transforms. But I assumed that I could convert back and forth between a `Matrix3` instance and the corresponding Euler angles; in practice I haven't been able to get this to work consistently, and can't explain the results I'm seeing. Here's a simple test case that can be run in a console app:

```c#
namespace NiflySharpTest
{
    class Program
    {
        static void Main(string[] args)
        {
            TestRotationRoundtrip(-0.525f, 0.00842f, 0.041f);
            TestRotationRoundtrip(0.123f, 0, 0.855f);
            TestRotationRoundtrip(0.123f, 0.414f, 0);
            TestRotationRoundtrip(0.123f, 0.414f, -0.075f);
        }

        private static void TestRotationRoundtrip(float y, float p, float r)
        {
            var rotation = new Rotation(y, p, r);
            var roundtrip = Rotation.FromMatrix3(rotation.ToMatrix3());
            Console.WriteLine($"{rotation} -> {roundtrip}");
        }
    }

    record Rotation(float Yaw, float Pitch, float Roll)
    {
        public static Rotation FromMatrix3(Matrix3 rotation)
        {
            float yaw = 0, pitch = 0, roll = 0;
            rotation.ToEulerAngles(ref yaw, ref pitch, ref roll);
            return new Rotation(yaw, pitch, roll);
        }

        public override string ToString()
        {
            return $"({Yaw:f5}, {Pitch:f5}, {Roll:f5})";
        }

        public Matrix3 ToMatrix3()
        {
            // Pitch and Yaw seem to be reversed.
            return Matrix3.MakeRotation(Pitch, Yaw, Roll);
        }
    }
}
```

Here's what the output looks like:

```
(-0.52500, 0.00842, 0.04100) -> (0.52434, -0.02896, -0.03549)
(0.12300, 0.00000, 0.85500) -> (-0.08095, 0.09271, -0.85124)
(0.12300, 0.41400, 0.00000) -> (-0.12300, -0.41400, -0.00000)
(0.12300, 0.41400, -0.07500) -> (-0.08986, -0.42197, 0.08160)
```

For the angles that seem to more-or-less work (i.e. allowing for some floating-point precision loss?), it seems to be flipping the sign, like `-0.525 -> 0.524`), but then some of the roundtrip angles I don't understand at all (`0.0 -> 0.09271`, `0.123 -> -0.081`, etc.).

I've intentionally switched the Y and P values in `MakeRotation`, because it looked like they were being transposed - you can try switching them back but it doesn't really improve the result. Also, if I negate all of the parameters in `MakeRotation`, I get different results but still not the ones I expect.

Is this just not the correct usage of the API, is it an issue in niflysharp, or an issue in nifly itself?

**Comment by SteveTownsend** [comment]
Comments in nifly source indicate that this is not expected to work, without clarifying what should be done to achieve your goal. I don't have time (or expertise) to dig into this further - you could try asking at the main repo for nifly to see if someone there can help you do what you want.

https://github.com/ousnius/nifly

In my fork this is at nifly\include\Object3d.hpp l.616 &ff.
```
	// Generate rotation matrix from yaw, pitch and roll (in radians)
	// This is not the inverse of ToEulerAngles; though both functions
	// work with Euler angles, there are many conflicting definitions
	// of "Euler angles" (yaw, pitch, and roll), and these two functions
	// use different definitions.
	static Matrix3 MakeRotation(const float yaw, const float pitch, const float roll);

	// Convert rotation to euler degrees (Yaw, Pitch, Roll)
	// This function assumes that the matrix is a rotation matrix.
	// ToEulerAngles is not the inverse of MakeRotation; though both
	// functions work with Euler angles, there are many conflicting
	// definitions of "Euler angles", and these two functions use
	// different definitions.
	// The return result "canRot" apparently means roll is not zero.
	bool ToEulerAngles(float& y, float& p, float& r) const;
```
